---
title: Stackbit Azimuth Theme
baseURL: "/"
params:
  palette: orange
  header:
    type: header
    template: header
    title: Azimuth
    logo_img: images/logo.png
    has_nav: true
    nav_links:
    - type: action
      template: action
      label: Home
      url: "/"
    - type: action
      template: action
      label: Features
      url: "/features"
    - type: action
      template: action
      label: Pricing
      url: "/pricing"
    - type: action
      template: action
      label: Style Guide
      url: "/style-guide"
    - type: action
      template: action
      label: Sign Up
      url: "/signup"
      primary: true
  footer:
    type: footer
    template: footer
    logo_img: images/logo_alt.png
    tagline: Wahaab Siddique.
    has_nav: true
    nav_title: Company
    nav_links:
    - type: action
      template: action
      label: About Us
      url: "/about"
    - type: action
      template: action
      label: Blog
      url: "/blog"
    - type: action
      template: action
      label: Sign Up
      url: signup
    - type: action
      template: action
      label: Contact
      url: "/contact"
    has_social: true
    social_title: Community
    social_links:
    - type: action
      template: action
      label: Twitter
      url: https://twitter.com/
      new_window: true
    - type: action
      template: action
      label: Instagram
      url: https://www.instagram.com/
      new_window: true
    - type: action
      template: action
      label: LinkedIn
      url: https://www.linkedin.com/
      new_window: true
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: "&copy; Stackbit. All rights reserved."
    links: []
taxonomies:
  stub: stub
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
